# 使用 code-server 作为基础镜像
FROM linuxserver/code-server:4.90.3

# 使用 root 用户执行命令
USER root

# 安装python3.11和pip
RUN apt-get update && \
    apt-get install -y python3.11 python3.11-distutils && \
    curl -sS https://bootstrap.pypa.io/get-pip.py | python3.11 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# 设置 /home/gengshang 映射到宿主机
VOLUME /home/gengshang

# 开放 8443 端口
EXPOSE 8443

# 设置环境变量
ENV PASSWORD=gengshang \
    LANG=en_US.UTF-8 \
    S6_VERBOSITY=1 \
    S6_STAGE2_HOOK=/docker-mods \
    PUID=1000 \
    PATH=/lsiopy/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
    TERM=xterm \
    S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0 \
    LSIO_FIRST_PARTY=true \
    TZ=Asia/Shanghai \
    SUDO_PASSWORD=p@ssw0rd \
    DEFAULT_WORKSPACE=/home/gengshang \
    VIRTUAL_ENV=/lsiopy \
    PGID=1000 \
    HOME=/config \
    LANGUAGE=en_US.UTF-8

# 设置入口点
ENTRYPOINT ["/init"]